# ruff.toml
# Vilken Python-version koden ska tolkas som
# (t.ex. "py39" för Python 3.9)
target-version = "py39"

# Maxlängd på kodrader (t.ex. 88 för att matcha Black-formattern)
line-length = 88

# Vilka regel-familjer som ska användas (E=pycodestyle, F=pyflakes)
lint.select = ["E", "F"]

# Regler att ignorera (E501 = för långa rader)
lint.ignore = ["E501"]

# Mappar som Ruff ska ignorera vid lintning
exclude = ["venv", "build", "__pycache__"]